### ISSUE TITLE
osgQt fails to build

### ISSUE THREAD

**Issue by TNick** [openscenegraph/osg#17]
The  [CMakeLists.txt](https://github.com/openscenegraph/osg/blob/master/src/osgQt/CMakeLists.txt#L11) has these lines

```
SET(SOURCES_H
    ${HEADER_PATH}/QGraphicsViewAdapter
)

IF ( Qt5Widgets_FOUND )
    QT5_WRAP_CPP( SOURCES_H_MOC ${SOURCES_H} OPTIONS "-f" )
ELSE()
    QT4_WRAP_CPP( SOURCES_H_MOC ${SOURCES_H} OPTIONS "-f" )
ENDIF()
```
For some weird reason moc fails with rather cryptic message: ```moc: Too many input files specified``` (all google results link to spaces in paths, which is not the case). The response file for moc looks like so:

```
-I"G:/prog/osg/3.2.1-rc1/include"
-I"G:/prog/osg/build-3.2.1-rc1/include"
-D_SCL_SECURE_NO_WARNINGS
-D_CRT_SECURE_NO_DEPRECATE
-DOSGQT_LIBRARY
-DWIN32
-f
-o
G:/prog/osg/build-3.2.1-rc1/src/osgQt/__/__/include/osgQt/moc_QGraphicsViewAdapter.cpp
G:/prog/osg/3.2.1-rc1/include/osgQt/QGraphicsViewAdapter
```
By removing the -f (that expects an argument) we can pass this step but compilation  hits another wall because of the lines 47-48 in BufferObject

```
typedef int GLintptr;
typedef int GLsizeiptr;
```
that redefine types defined in Qt's own implementation of OpenGL.

**Comment by wdoo01** [comment]
try
````
IF ( Qt5Widgets_FOUND ) 
    QT5_WRAP_CPP( SOURCES_H_MOC ${SOURCES_H} OPTIONS "-fosgQt/QGraphicsViewAdapter" ) 
ELSE() 
    QT4_WRAP_CPP( SOURCES_H_MOC ${SOURCES_H} OPTIONS "-f" )
````
I found it from http://bbs.osgchina.org/forum.php?mod=viewthread&tid=13202 (Chinese)
But I don't know why
