### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [openscenegraph/osg#19]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [AutoDiscovery](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/ZeroConfDevice/AutoDiscovery.cpp#L29 "destructor for AutoDiscovery")
* [CMFC_OSG_MDIView::OnDestroy](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/examples/osgviewerMFC/MFC_OSG_MDIView.cpp#L76 "CMFC_OSG_MDIView::OnDestroy function")
* [FieldReaderIterator::_free](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgDB/FieldReaderIterator.cpp#L44 "FieldReaderIterator::_free function")
* [Mesh::clear](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/x/mesh.cpp#L55 "Mesh::clear function")
* [QuicktimeImportExport::readFromStream](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/quicktime/QTImportExport.cpp#L189 "QuicktimeImportExport::readFromStream function")
* [RawImageClose](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/rgb/ReaderWriterRGB.cpp#L134 "RawImageClose function")
* [simage_pic_load](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/pic/ReaderWriterPIC.cpp#L101 "simage_pic_load function")
* [trpgRange::Reset](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/txp/trpage_range.cpp#L53 "trpgRange::Reset function")

**Comment by openscenegraph** [comment]
These are just coding style changes, the original code is fine even if it's not optimal. Changing code for the sake of it can easily introduce bugs so unless there is a specific issue I will not be chasing up these code changes.
