### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [openscenegraph/osg#20]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "reposition a file-position indicator") ⇒ [simage_pic_load](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/pic/ReaderWriterPIC.cpp#L101)
- [ftell](http://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "return a file offset") ⇒ [trpgwAppFile::Init](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgPlugins/txp/trpage_writebuf.cpp#L340)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "initialise a mutex") ⇒ [Barrier](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/OpenThreads/pthreads/PThreadBarrier.cpp#L46 "constructor for Barrier")

**Comment by openscenegraph** [comment]
If there are specific issues that need discussing please use the official osg-users mailing list/forum.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?
