### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [openscenegraph/osg#21]
I guess that a different program design will be needed for your function "[signalHandler](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/applications/osgfilecache/osgfilecache.cpp#L384 "Check signal handling implementation")".
* The variable "s_ExitApplication" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/seccode/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.") (instead of "bool").
* The function "[printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "print formatted output")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by openscenegraph** [comment]
Fix now checked in to git master.
https://github.com/openscenegraph/osg/commit/86137e5ac1e50ab04b02ebdf99d533deab112200#diff-d16ffbf0afebd151bf2a081d2ea256e2

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/openscenegraph/osg/commit/86137e5ac1e50ab04b02ebdf99d533deab112200 "Safer signal handling").
