### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [openscenegraph/osg#22]
Some parameters (like "[${CMAKE_BINARY_DIR}/Android.mk](https://github.com/openscenegraph/osg/blob/4ed195a236856dfbe446a070ad1165a23851b621/CMakeLists.txt#L129)" and "[${HEADER_PATH}/DataTypes](https://github.com/openscenegraph/osg/blob/efff444beca9faa7a2680efb1dd6e0b7db170c1e/src/osgDB/CMakeLists.txt#L45)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by openscenegraph** [comment]
If you have specific changes then please make changes and submit, if you want to have general discussion then please use the official user-users mailing list/forum.
