### ISSUE TITLE
Collada plugin support

### ISSUE THREAD

**Issue by chrischoy** [openscenegraph/osg#25]
Hi I'm trying to use new collada plugin from

> http://collada.org/mediawiki/index.php/DOM_guide:_Setting_up

specifically, the `svn co https://collada-dom.svn.sourceforge.net/svnroot/collada-dom/trunk colladadom`

When I setup the colladadom include path and library path and configure and make I get this error message. Usually about the namespace issue 

> osg/src/osgPlugins/dae/daeReader.h:162:5: error: unknown type name 'domUpAxisType'; did you mean 'ColladaDOM141::domUpAxisType'?

and enum type specification issues.

> /Users/chrischoy/packages/osg/src/osgPlugins/dae/daeReader.h:359:61: error: C++ requires a type specifier for all declarations
    osg::Image* processImageTransparency(const osg::Image*, domFx_opaque_enum, float transparency) const;

> /Users/chrischoy/packages/osg/src/osgPlugins/dae/daeReader.h:360:154: error: C++ requires a type specifier for all declarations
    osg::Texture2D* processTexture( ColladaDOM141::domCommon_color_or_texture_type_complexType::domTexture *tex, const osg::StateSet*, TextureUnitUsage, domFx_opaque_enum = FX_OPAQUE_ENUM_A_ONE, f...
                                                               
Complaining about missing type of domFx_opaque_enum

**Comment by openscenegraph** [comment]
Please use the latest OSG for build, and use the official osg-users mailing list/forum for support.
