### ISSUE TITLE
osgConv crashed when trying to convert fbx with binding material

### ISSUE THREAD

**Issue by skylook** [openscenegraph/osg#26]
The fbx file is as follows:
http://pan.baidu.com/s/1pJI61YF

When trying to convert with the current version (3.3.3) of osgConv it crashed.
I have tried both fbx sdk 2015 and 2014.

My system is Mac OSX 10.10 with Xcode 6.1。

Any solution for that?

**Comment by openscenegraph** [comment]
Please user latest OSG-3.4 for testing, and the osg-users mailing list/forum for support questions.
