### ISSUE TITLE
On linux 'sudo make install' fails to install osgViewer/config/ header files.

### ISSUE THREAD

**Issue by Factoid** [openscenegraph/osg#27]
Not sure if I'm doing something wrong, but building and installing osg from the git repo doesn't seem to install the /usr/local/include/osgViewer/config folder, which prevents me from referencing the SingleWindow and other ViewConfig classes.

**Comment by openscenegraph** [comment]
A fix for installing the include/osgViewer/config files has now been checked into master and the OpenSceneGraph-3.4 branches.
