### ISSUE TITLE
On Linux, declaring an osgViewer::Viewer object globally segfaults when exiting via 'esc' - ver. 3.2.2

### ISSUE THREAD

**Issue by Factoid** [openscenegraph/osg#28]
```
osgViewer::Viewer viewer;

int main( int argc, char** argv) {
  viewer.apply( new osgViewer::SingleWindow(0,0,640,480) );
  viewer.run();
}
```
The above program will exit normally if closed by clicking the 'close' button, but will segfault on a mutex lock if closed via 'esc'. Moving the viewer declaration inside main fixes it.

When closing via the close button it never enters the loop in GLBufferObjectManager::deleteAllGLBufferObjects()

When closing via esc it does. I suspect that closing the window frees buffer objects in a way that hitting 'esc' doesn't, and that the viewer needs to issue a call to destroy the window. Making the viewer local to main must allow proper cleanup to occur before the program completely terminates.

Maybe it's a non issue, but I thought I'd bring it to your attention.

**Comment by openscenegraph** [comment]
The usage case is what I'd describe as bad programming and is recommend against.  I put this issue under "do stupid stuff and undefined behaviour might happen".  The fix is simply put the Viewer in the main so clean up happens is well defined way.
