### ISSUE TITLE
OSG3.3.4 and OSG3.3.5 cannot display text on android

### ISSUE THREAD

**Issue by coordinate** [openscenegraph/osg#30]
OSG3.3.3 is OK.
But OSG3.3.4 and OSG3.3.5 cannot display text on android.
It output a lot of:
W/Osg Viewer: Warning: detected OpenGL error 'invalid enumerant' at Before Renderer::compile.

**Comment by openscenegraph** [comment]
Could you update to OSG-3.4 or master and see if problem remains.  As a general note, the best place to post reports is on the official osg-users mailing list/forum.
