### ISSUE TITLE
Support for gtkglext-quartz on Mac OS X

### ISSUE THREAD

**Issue by tschoonj** [openscenegraph/osg#34]
Hi,

Could you please provide support for gtkglext that was built against the gtk2 quartz backend in the CMake scripts?
I am currently revising the openscenegraph formula for Homebrew to ensure it builds properly against our soon to be released revised gtk+ formula, which will be quartz backend ONLY.

For now I managed to fix the problem using the following hack, but ideally a proper detection of the gtkglext version would be necessary.

Thanks in advance!

````diff
diff --git a/CMakeModules/FindGtkGl.cmake b/CMakeModules/FindGtkGl.cmake
index 321cede..6497589 100644
--- a/CMakeModules/FindGtkGl.cmake
+++ b/CMakeModules/FindGtkGl.cmake
@@ -10,7 +10,7 @@ IF(PKG_CONFIG_FOUND)
     IF(WIN32)
         PKG_CHECK_MODULES(GTKGL gtkglext-win32-1.0)
     ELSE()
-        PKG_CHECK_MODULES(GTKGL gtkglext-x11-1.0)
+        PKG_CHECK_MODULES(GTKGL gtkglext-quartz-1.0)
     ENDIF()
 
 ENDIF()
````

**Comment by openscenegraph** [comment]
The suggested change will break build against older variants of Gtk so is not suitable as is.  Which OS variant are you using?  What is the Gtk version?

**Comment by tschoonj** [comment]
This applies only to Mac OS X. Homebrew is now using a version of Gtk2 (2.24.28) that only supports the quartz backend.

Instead of using the `IF(WIN32)` block, it makes far more sense to retrieve from the gtk pkg-config file which backend it was compiled against. Something like this:

````
pkg-config --variable=target gtk+-2.0
````

This will return win32, x11, quartz and possibly other values. Next use this value to determine which gtkglext version you need as the same backend name ends up in its pkg-config module name.

**Comment by openscenegraph** [comment]
Just tried : 

   pkg-config --variable=target gtk+-2.0

On my Kubunutu command line and got no return information.   Could you please provide a practical suggestion for modifying CMake?

The other option we have is to simply disable the osgviewGTK example under OSX, as it's a really niche example.

**Comment by tschoonj** [comment]
It works on my Mac OS X and on CentOS 6. What version of KUbuntu and gtk2 are you running?

Unfortunately I don't really know any cmake, so I cannot really help you out with that.

**Comment by openscenegraph** [comment]
I am using Kubuntu 14.04 right now, turns out that gtk2 isn't installed which is probably why pkg-config didn't pick up on it.

Do any errors actually occur with the OSG buiild as is?  From the look of it I'd expect the PKG_CHECK_MODULES(GTKGL gtkglext-x11-1.0) to fail on your OSX system and for it to simply not build the osgviewerGTK example.

While I could still build if we added some extra checks to the FindGtkGL.cmake for your particular OSX setup, I don't see a single niche example as something that would be a problem for vast majority of OSG users.  If you are such a niche user then an extra hurdle for one specific GTK based example is not something I'd worry about.

**Comment by tschoonj** [comment]
Well I have to admit that I am not an OSG user at all :flushed: 

I merely made sure the existing Homebrew OSG formula would provide support for the gtk quartz backend after we transitioned to supporting only the quartz backend. Interestingly the OSG formula marks gtkglext as a mandatory dependency, which apparently is not really true. If you are not willing to provide support for gtkglext-quartz, I will just remove the dependency from the formula completely, something I could certainly live with (but maybe others won't :smile:).

**Comment by openscenegraph** [comment]
The first step would be to remove the dependency spec from the Homebrew OSG forumula.  The vast majority of OSG external dependencies are optional.  The core OSG needs Standard C++ and OpenGL and  zlib for the osgDB library.  The rest of the dependencies are optional with the CMake build system toggling on/off components depending on the availability of various 3rd party dependencies.

I'm open to supporting gtkext-quartz backend but don't have an OSX machine so have to rely upon OSX users to provide the solution.  If you don't have the CMake expertise and no one else in the OSX/OSG community has any need/interest then it would be best just to close this issue as it doesn't appear to be directly affecting any active users.

For now I'll close this issue, if you want to open it again I would suggest joining the osg-users mailing list/forum and discussing the topic with the wider community to bring in the opinions/expertise of other OSX users.

**Comment by tschoonj** [comment]
Thanks for you thoughts on this issue.

I think that for now I will keep the hack in the Homebrew formula alive until someone opens a PR here with a more permanent fix. This way I won't have to deal with users complaining about the missing GTK example :smile:
