### ISSUE TITLE
Viewer on Multi-Monitor system crashes without --screen parameter using OSG 3.4.0

### ISSUE THREAD

**Issue by beachwalker** [openscenegraph/osg#37]
If you have a multi-monitor setup (e.g. 2 Monitors attached) running the latest stable release 3.4.0 of OpenSceneGraph, the application crashed at startup when no --screen parameter is set. (OSG tries to use all monitors by default, worked with 3.2.3) This doesn't happen if you explicitely call osgviewer --screen 0 to start rendering only at one screen.

**Comment by openscenegraph** [comment]
The following up on osg-users didn't come up with anyone who could reproduce the problem using similar setup so I'm going to close this issue as most likely cause is a OpenGL driver bug which is out with the scope of the OSG.

**Comment by jhpark16** [comment]
I have a similar issue with OSG 3.1.0, 3.4.0, and 3.4.1. The OSGviewer crashed when I rotated the object with a mouse.  I am using GeForce GTX 1050 Ti and Nvidia driver 385.41.

**Comment by jhpark16** [comment]
OSGviewer is working fine with --screen 0. I have a dual monitor setup.
