### ISSUE TITLE
how to extract decompress images from an IVE

### ISSUE THREAD

**Issue by yingyue219** [openscenegraph/osg#40]
OSG issue : I have a question about extracting images from an IVE with compressed textures. 
osg::Texture2D *texture2D = dynamic_cast
(geometry->getOrCreateStateSet()->getTextureAttribute(0, osg::StateAttribute::TEXTURE));
osg::ref_ptrosg::Image image = texture2D->getImage();//but image is compressed

**Comment by ChrisDenham** [comment]
Not sure if it helps, but I recall a conversation I had about this a few years back on the OpenSceneGraph forum. http://forum.openscenegraph.org/viewtopic.php?t=8599

**Comment by yingyue219** [comment]
I have solved this issue with off screen rendering 
glCompressedTexImage2D;
then using glReadPixels achieve the texture image!

**Comment by yingyue219** [comment]
I have solved this issue with off screen rendering 
glCompressedTexImage2D;
then using glReadPixels achieve the texture image or glgettexImage
