### ISSUE TITLE
how to compress or decompress image texture using OpenScenGraph ?

### ISSUE THREAD

**Issue by yingyue219** [openscenegraph/osg#43]
I find following functions:

CompressDXT.h(45):void compressDXT3(const nvtt::OutputOptions::Private & outputOptions);
 CompressDXT.h(64):void compressDXT3(const nvtt::CompressionOptions::Private & compressionOptions, const nvtt::OutputOptions::Private & outputOptions);
 OptimalCompressDXT.h(44):	void compressDXT3A(const ColorBlock & rgba, AlphaBlockDXT3 * dxtBlock);
 QuickCompressDXT.h(43):void compressDXT3(const ColorBlock & rgba, BlockDXT3 * dxtBlock);
 CompressDXT.h(45):void compressDXT3(const nvtt::OutputOptions::Private & outputOptions);
 CompressDXT.h(64):void compressDXT3(const nvtt::CompressionOptions::Private & compressionOptions, const nvtt::OutputOptions::Private & outputOptions);
 OptimalCompressDXT.h(44):	void compressDXT3A(const ColorBlock & rgba, AlphaBlockDXT3 * dxtBlock);
 QuickCompressDXT.h(43):void compressDXT3(const ColorBlock & rgba, BlockDXT3 * dxtBlock);

how to use those functions？  how to  compress or decompress image texture using OpenScenGraph ?and how to make jpg texture image maintain jpg format,then make ive or osgb file smaller?

**Comment by openscenegraph** [comment]
Please use official osg-users mailing list/forum for support.
