### ISSUE TITLE
how to using  atlas of openscenegraph?

### ISSUE THREAD

**Issue by yingyue219** [openscenegraph/osg#45]
how to using  atlas of openscenegraph? make many little texture images merge to a large image!?
osgUtil::Optimizer::TextureAtlasBuilder::Atlas?

**Comment by openscenegraph** [comment]
Please user official mailing list/forum for support.

**Comment by yingyue219** [comment]
std::vector<std::string> imgfileNames;
	CBrowseDirBase().BrowseCurrentPathFile("..\\image\\","*.bmp",imgfileNames);
	osgUtil::Optimizer::TextureAtlasBuilder atlasBuilder;
	atlasBuilder.setMaximumAtlasSize(4096, 4096);
	for (size_t i = 0; i < imgfileNames.size(); i++)
	{
		atlasBuilder.addSource(osgDB::readImageFile(imgfileNames[i]));
	}
	atlasBuilder.buildAtlas();
	osg::Image *image = atlasBuilder.getImageAtlas(unsigned int( 0));
	osg::Matrix m =  atlasBuilder.getTextureMatrix(unsigned int(0));
	
	osgDB::writeImageFile(*image, "tt.jpg");
