### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [openscenegraph/osg#46]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidate:
[AutoDiscovery](https://github.com/openscenegraph/osg/blob/ca94bd0a65d6a4c32f458552bdca66d3d8ebc136/src/osgPlugins/ZeroConfDevice/AutoDiscovery.cpp#L29 "AutoDiscovery class")

**Comment by openscenegraph** [comment]
If you want to discuss topics pleas use the official osg-users mailing list/forum and NOT abuse the gitbhub issues system.

**Comment by scrawl** [comment]
@openscenegraph @robertosfield : you can go to repository settings and disable the "Issues" feature, thus preventing anyone from posting here.
