### ISSUE TITLE
Fails to find default collada-dom include directory on OS X 10.9.5

### ISSUE THREAD

**Issue by apjanke** [openscenegraph/osg#48]
When trying to build OpenSceneGraph with collada-dom 2.4 installed on OS X 10.9.5, I get a build failure where it complains about a missing `dae.h`.

```
[ 86%] Building CXX object src/osgPlugins/dae/CMakeFiles/osgdb_dae.dir/daeReader.cpp.o
cd /tmp/open-scene-graph20150903-1074-ipfyil/OpenSceneGraph-3.4.0/build/src/osgPlugins/dae && /usr/local/Library/ENV/4.3/clang++   -DCOLLADA_DOM_SUPPORT141 -DNO_BOOST -Dosgdb_dae_EXPORTS -std=c++11 -stdlib=libc++  -Wno-conversion -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fPIC -I/tmp/open-scene-graph20150903-1074-ipfyil/OpenSceneGraph-3.4.0/include -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -I/tmp/open-scene-graph20150903-1074-ipfyil/OpenSceneGraph-3.4.0/build/include -I/usr/local/opt/collada-dom/include/collada-dom -I/usr/local/opt/collada-dom/include/collada-dom/1.4    -o CMakeFiles/osgdb_dae.dir/daeReader.cpp.o -c /tmp/open-scene-graph20150903-1074-ipfyil/OpenSceneGraph-3.4.0/src/osgPlugins/dae/daeReader.cpp
In file included from /tmp/open-scene-graph20150903-1074-ipfyil/OpenSceneGraph-3.4.0/src/osgPlugins/dae/daeReader.cpp:14:
/tmp/open-scene-graph20150903-1074-ipfyil/OpenSceneGraph-3.4.0/src/osgPlugins/dae/daeReader.h:19:10: fatal error: 'dae.h' file not found
#include <dae.h>
         ^
```

The default installation of `collada-dom` for newer versions (2.2, 2.4), when built from source, looks like it will install its headers in a version-qualified subdirectory under `include`, like `include/collada-dom2.2` or `include/collada-dom2.4`, not `include/collada-dom`.

But [`CMakeModules/FindCOLLADA.cmake`](https://github.com/openscenegraph/osg/blob/master/CMakeModules/FindCOLLADA.cmake) is [only looking for non-version-qualified dirs](https://github.com/openscenegraph/osg/blob/bb69e429538678cc1e7a9fa291fd519dadb36f8f/CMakeModules/FindCOLLADA.cmake#L46-L66).

```
    /usr/local/include/colladadom
    /usr/local/include/collada-dom
    /opt/local/include/collada-dom
    /usr/include/
    /usr/include/colladadom
    /usr/include/collada-dom
```

This was noticed when doing a build in Homebrew; see homebrew/homebrew#43536 for details if you're curious.

It seems like the CMake scripts should be modified to look for `collada-dom2.*`, to work smoothly with the default collada-dom installation.

Specifying `-DCOLLADA_INCLUDE_DIR` doesn't seem to be sufficient to get this working. I tried `cmake -DCMAKE_INSTALL_PREFIX=/tmp/test-open-scene-graph -DCOLLADA_INCLUDE_DIR=/usr/local/opt/collada-dom/include/collada-dom2.4 .. | tee cmake.log`. When i do that, it no longer errors out on a missing `dae.h`, but fails to find another header from the `1.4` DOM subdirectory.

```
[ 87%] Building CXX object src/osgPlugins/dae/CMakeFiles/osgdb_dae.dir/daeReader.cpp.o
cd /tmp/open-scene-graph20151126-78498-1ygkfdp/OpenSceneGraph-3.4.0/build/src/osgPlugins/dae && /usr/local/Library/ENV/4.3/clang++   -DCOLLADA_DOM_SUPPORT141 -DNO_BOOST -Dosgdb_dae_EXPORTS -I/tmp/open-scene-graph20151126-78498-1ygkfdp/OpenSceneGraph-3.4.0/include -F/Applications/Xcode-6.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks -I/tmp/open-scene-graph20151126-78498-1ygkfdp/OpenSceneGraph-3.4.0/build/include -I/usr/local/opt/collada-dom/include/collada-dom2.4 -I/1.4  -std=c++11 -stdlib=libc++  -Wno-conversion -arch x86_64 -isysroot /Applications/Xcode-6.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -fPIC   -o CMakeFiles/osgdb_dae.dir/daeReader.cpp.o -c /tmp/open-scene-graph20151126-78498-1ygkfdp/OpenSceneGraph-3.4.0/src/osgPlugins/dae/daeReader.cpp
In file included from /tmp/open-scene-graph20151126-78498-1ygkfdp/OpenSceneGraph-3.4.0/src/osgPlugins/dae/daeReader.cpp:14:
/tmp/open-scene-graph20151126-78498-1ygkfdp/OpenSceneGraph-3.4.0/src/osgPlugins/dae/daeReader.h:22:10: fatal error: 'dom/domCommon_color_or_texture_type.h' file not found
#include <dom/domCommon_color_or_texture_type.h>
         ^
```

That `-I/usr/local/opt/collada-dom/include/collada-dom2.4 -I/1.4` looks like something's falling through the cracks with detecting the DOM root dir. Here's what I see after running that `cmake`.

```
$ grep -r COLLADA_DOM_R *
CMakeCache.txt:COLLADA_DOM_ROOT:PATH=/include/1.4/dom
$ grep -r COLLADA_INCL *
CMakeCache.txt:COLLADA_INCLUDE_DIR:PATH=/usr/local/opt/collada-dom/include/collada-dom2.4
CMakeCache.txt:COLLADA_INCLUDE_DOMANY_DIR:PATH=/usr/local/opt/collada-dom/include/collada-dom2.4
```

Looks like it's [this code in FindCOLLADA.cmake](https://github.com/openscenegraph/osg/blob/bb69e429538678cc1e7a9fa291fd519dadb36f8f/CMakeModules/FindCOLLADA.cmake#L17-L23), which doesn't match up with the locations for an installed collada-dom or use `COLLADA_INCLUDE_DIR` to locate the DOM includes. 

```
# Check if COLLADA_DIR is set, otherwise use ACTUAL_3DPARTY_DIR:
SET( COLLADA_ENV_VAR_AVAILABLE $ENV{COLLADA_DIR} )
IF ( COLLADA_ENV_VAR_AVAILABLE )
    SET(COLLADA_DOM_ROOT "$ENV{COLLADA_DIR}/dom" CACHE PATH "Location of Collada DOM directory" FORCE)
ELSE ()
    SET(COLLADA_DOM_ROOT "${ACTUAL_3DPARTY_DIR}/include/1.4/dom" CACHE PATH "Location of Collada DOM directory" FORCE)
ENDIF()
```

**Comment by openscenegraph** [comment]
I have add checks against the collada-dom2.2 + collado-dom2.4 to the FindCOLLADA.cmake and checked this into master, OSG-3.4 and OSG-3.2 branches.  This works with recent COLLADA dom under Linux, but as I don't have a OSX system will have to defer to the community for testing.  The right place to discuss this issue further is on the osg-users mailing list/forum as the more of the community can pitch in.
