### ISSUE TITLE
fail to compile osg

### ISSUE THREAD

**Issue by gzliudan** [openscenegraph/osg#52]
ffmpeg is cloned from https://github.com/FFmpeg/FFmpeg.git

After config osg with cmake-gui, when I run make, it reports below erros:

/root/osg/OpenSceneGraph-3.4.0/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp: In member function ‘void osgFFmpeg::FFmpegDecoderAudio::open(AVStream*, osgFFmpeg::FFmpegParameters*)’:
/root/osg/OpenSceneGraph-3.4.0/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:230:20: error: ‘AVCodecContext’ has no member named ‘get_buffer’
         m_context->get_buffer = avcodec_default_get_buffer;
                    ^
/root/osg/OpenSceneGraph-3.4.0/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:230:33: error: ‘avcodec_default_get_buffer’ was not declared in this scope
         m_context->get_buffer = avcodec_default_get_buffer;
                                 ^
/root/osg/OpenSceneGraph-3.4.0/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:231:20: error: ‘AVCodecContext’ has no member named ‘release_buffer’
         m_context->release_buffer = avcodec_default_release_buffer;
                    ^
/root/osg/OpenSceneGraph-3.4.0/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:231:37: error: ‘avcodec_default_release_buffer’ was not declared in this scope
         m_context->release_buffer = avcodec_default_release_buffer;
                                     ^
make[2]: *** [src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o] Error 1
make[1]: *** [src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/all] Error 2
make: *** [all] Error 2

**Comment by openscenegraph** [comment]
The FFmpeg API has changed again since the OSG_3.4.0 release so you'll need to use an older version of FFmpeg to compile against OSG-3.4.0.
