### ISSUE TITLE
Enumeration HttpAuthentication incorrect

### ISSUE THREAD

**Issue by martin-s** [openscenegraph/osg#56]
If it's related to curl NTLM and GSSNegotiate should be switched:
https://github.com/openscenegraph/osg/blob/ca94bd0a65d6a4c32f458552bdca66d3d8ebc136/include/osgDB/AuthenticationMap#L39

**Comment by robertosfield** [comment]
Thanks for the note, I had updated the enum values to match with the latest in libcurl.  Fix checked into master and 3.2 and 3.4 branches.
