### ISSUE TITLE
Please update the ffmpeg detection/plugin for v.1.x+ otherwise compilation fails (solution included)

### ISSUE THREAD

**Issue by ChristianFrisson** [openscenegraph/osg#6]
I tried compiling osgdb_ffmpeg on OSX using ffmpeg 1.0 from MacPorts, it fails with OSX 10.6.8 and Xcode 3.2.6 and OSX 10.7.5 and Xcode 4.5.

It seems that ffmpeg now ships a header file called "time.h" in libavutil, and the compiler gets to include this one before its own. 

`osg/CMakeModules/FindFFmpeg.cmake` reads:
#In ffmpeg code, old version use `#include <header.h>` and newer use `#include <libname/header.h>`
#In OSG ffmpeg plugin, we use `#include <header.h>` for compatibility with old version of ffmpeg

I would suggest to modify FindFFmpeg.cmake so as to use `#include <libname/header.h>` only, as I did for a fork in shotdetect:
https://github.com/johmathe/Shotdetect/commit/ffb85ed99cb30d0ed292b20fd187017d27e09527

Then, ffmpeg includes in `osg/src/osgPlugins/ffmpeg/FFmpegHeaders.hpp` can be adapted accordingly.

What do you think?

**Comment by openscenegraph** [comment]
OSG-3.4 should address this build issues with ffmpeg.
