### ISSUE TITLE
Please add support for Qt5

### ISSUE THREAD

**Issue by anycad** [openscenegraph/osg#7]
Please add support for Qt5

**Comment by openscenegraph** [comment]
Qt5 support is provided in OSG-3.4 onwards.

**Comment by epot** [comment]
Sorry for the dumb question, but does it mean that we should not have the issue with Qt5 and multithreading (crashing at starting with the message "Cannot make QOpenGLContext current in a different thread") ? Because it seems I still have the issue with OSG 3.4. Should I open another ticket ?

**Comment by openscenegraph** [comment]
Please use the osg-users mailing list or forum for support questions like this.

As a general note, not all versions of Qt5 behave the same, as various discussions of osg-users mailing list/forum have discussed.

**Comment by airscrat** [comment]
If you want use multithreading in Qt5, you can set QCoreApplication's attribute like this:
coreApp->setAttribute(Qt::AA_DontCheckOpenGLContextThreadAffinity);
coreApp is an QCoreApplication instance.
